{
    "dependencies": [
        {
            "path": "boost.assert",
            "versions": "1.68.0"
        },
        {
            "path": "boost.config",
            "versions": "1.68.0"
        },
        {
            "path": "boost.core",
            "versions": "1.68.0"
        },
        {
            "path": "boost.move",
            "versions": "1.68.0"
        },
        {
            "path": "boost.predef",
            "versions": "1.68.0"
        },
        {
            "path": "boost.preprocessor",
            "versions": "1.68.0"
        },
        {
            "path": "boost.smart_ptr",
            "versions": "1.68.0"
        },
        {
            "path": "boost.static_assert",
            "versions": "1.68.0"
        },
        {
            "path": "boost.throw_exception",
            "versions": "1.68.0"
        },
        {
            "path": "boost.tuple",
            "versions": "1.68.0"
        },
        {
            "path": "boost.type_traits",
            "versions": "1.68.0"
        }
    ],
    "path": "org.sw.demo.boost.exception",
    "source": {
        "git": {
            "commit": "dcd2d83b34458fef1b3b836d13fa4ee9429a8bec",
            "url": "https://github.com/boostorg/exception"
        }
    },
    "version": "1.68.0"
}